# https://github.com/opensearch-project/helm-charts
# https://github.com/opensearch-project/helm-charts/tree/main/charts/opensearch

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opensearch
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://opensearch-project.github.io/helm-charts/'
    chart: opensearch
    targetRevision: 3.2.1
    helm:
      releaseName: foxids-opensearch
      valuesObject:
        clusterName: foxids-opensearch
        nodeGroup: single
        masterService: foxids-opensearch-master
        roles:
          - master
          - ingest
          - data
          - remote_cluster_client
        replicas: 1
        persistence:
          enabled: true
          size: 20Gi
        resources:
          requests:
            cpu: "200m"
            memory: "768Mi"
          limits:
            cpu: "400m"
            memory: "1024Mi"
        extraEnvs:
          - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: opensearch-secret
                key: opensearch-admin-password
        sysctlVmMaxMapCount: 262144
        sysctlInit:
          enabled: true
        ingress:
          enabled: false
  destination:
    name: in-cluster
    namespace: foxids
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true