# https://medium.com/@shashwatmahar12/kubernetes-install-mongodb-from-helm-cron-job-to-backup-mongodb-replica-set-5fd8df51fe93  
# https://medium.com/@blackhorseya/deploying-mongodb-to-kubernetes-with-bitnamis-helm-chart-9c4f11eca24a  
# https://artifacthub.io/packages/helm/bitnami/mongodb
# https://github.com/bitnami/charts/blob/main/bitnami/mongodb/values.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'registry-1.docker.io/bitnamicharts'
    chart: mongodb
    targetRevision: 16.5.14
    helm:
      valuesObject:
        architecture: replicaset
        replicaSetName: mongodb
        replicaCount: 3
        persistence:
          size: 16Gi  
        resources:
          requests:
            cpu: 1
            memory: 4Gi
          limits:
            cpu: 4
            memory: 8Gi
        metrics:
          enabled: true
        arbiter:
          enabled: false
        auth:
          enabled: true
          existingSecret: mongodb-secret
          databases: 
            - FoxIDs
          usernames: 
            - foxids
        networkPolicy:
          extraIngress:
            - ports:
                - port: 15008 # Support Istio Ambient on port 15008
  destination:
    name: in-cluster
    namespace: foxids
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true