apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
  annotations:
    argocd.argoproj.io/hook: Sync
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ITfoxtec/FoxIDs.Kubernetes-CD.git
    targetRevision: main
    path: multi_nodes/app/foxids-db/mongodb
  destination:
    name: in-cluster
    namespace: foxids
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true