# https://artifacthub.io/packages/helm/bitnami/opensearch 
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opensearch
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'registry-1.docker.io/bitnamicharts'
    chart: opensearch
    targetRevision: 2.0.3
    helm:
      valuesObject:
        master:
          replicaCount: 2
          persistence:
            size: 22Gi
          # resources:
          #   limits:
          #     cpu: "750m"
          #     memory: "768Mi"
          #   requests:
          #     cpu: "500m"
          #     memory: "512Mi"
          metrics:
            enabled: true
          networkPolicy:
            #enabled: false
            extraIngress:
              - ports:
                  - port: 15008 # Support Istio Ambient on port 15008
        data: 
          replicaCount: 2
          persistence:
            size: 23Gi
          # resources:
          #   limits:
          #     cpu: "750m"
          #     memory: "1536Mi"
          #   requests:
          #     cpu: "500m"
          #     memory: "1024Mi"
          metrics:
            enabled: true
          networkPolicy:
            #enabled: false
            extraIngress:
              - ports:
                  - port: 15008 # Support Istio Ambient on port 15008
        coordinating: 
          replicaCount: 2
          # resources:
          #   limits:
          #     cpu: "750m"
          #     memory: "768Mi"
          #   requests:
          #     cpu: "500m"
          #     memory: "512Mi"
          metrics:
            enabled: true
          networkPolicy:
            #enabled: false
            extraIngress:
              - ports:
                  - port: 15008 # Support Istio Ambient on port 15008
        ingest: 
          replicaCount: 2
        #  tls: true
        #  selfSigned: true
          # resources:
          #   limits:
          #     cpu: "750m"
          #     memory: "768Mi"
          #   requests:
          #     cpu: "500m"
          #     memory: "512Mi"
          metrics:
            enabled: true
          networkPolicy:
            #enabled: false
            extraIngress:
              - ports:
                  - port: 15008 # Support Istio Ambient on port 15008
        dashboards:
          enabled: true
          replicaCount: 1
          # tls:
          #  enabled: true
          #  autoGenerated: true
          ingress:
            enabled: true
            hostname: "opensearch.test-single-nodes.foxids.com"
            annotations: 
              #nginx.ingress.kubernetes.io/whitelist-source-range: "xxx.xxx.xxx.xxx" # whitelist office IP address
              nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
              nginx.ingress.kubernetes.io/proxy-buffer-size: "32k"
              cert-manager.io/cluster-issuer: "letsencrypt" 
              # nginx.ingress.kubernetes.io/secure-backends: "true"
              # nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
            tls: true
            ingressClassName: nginx
          # resources:
          #   limits:
          #     cpu: "750m"
          #     memory: "768Mi"
          #   requests:
          #     cpu: "500m"
          #     memory: "512Mi"
          networkPolicy:
            #enabled: false
            extraIngress:
              - ports:
                  - port: 15008 # Support Istio Ambient on port 15008
        security:
          enabled: true
          existingSecret: opensearch-secret
          tls:
            autoGenerated: true
            restEncryption: true
            verificationMode: "certificate"
  destination:
    name: in-cluster
    namespace: foxids
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true