apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: meta-application
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - path: single_nodes/app
    repoURL: ${url}
    targetRevision: main
    directory:
      include: application.yaml
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
