apiVersion: apps/v1
kind: Deployment
metadata:
  name: foxids-deployment
  labels:
    app: foxids
spec:
  replicas: 3
  selector:
    matchLabels:
      app: foxids
  template:
    metadata:
      labels:
        app: foxids
    spec:
      containers:
        - name: foxids
          #image: foxids/foxids:2.2.2
          image: foxids/foxids:latest-test
          imagePullPolicy: Always
          ports:
            - containerPort: 8800
          env:
            - name: "Settings__UseHttp"
              value: "true"
            - name: "ASPNETCORE_URLS"
              value: "http://+:8800"
            - name: "Settings__UseHttp"
              value: "true"
            - name: "Settings__TrustProxyHeaders"
              value: "true"
            - name: "Settings__TrustProxySchemeHeader"
              value: "true"
            - name: "Settings__FoxIDsEndpoint"
              value: "https://id.test-multi-nodes.foxids.com" 
            - name: "Settings__Address__CompanyName"
              value: "My company name"
            - name: "Settings__Address__AddressLine1"
              value: "My company address"
            - name: "Settings__Address__PostalCode"
              value: "0000"
            - name: "Settings__Address__City"
              value: "My company city"
            - name: "Settings__Address__Country"
              value: "My company country"
            # - name: "Settings__Smtp__FromEmail"
            #   value: "xxx@my-domain.com"
            # - name: "Settings__Smtp__FromName" # Optional from name associated to the email address 
            #   value: "My company name"
            # - name: "Settings__Smtp__Host"
            #   value: "xxx.xxx"
            # - name: "Settings__Smtp__Port"
            #   value: "465"
            # - name: "Settings__Smtp__Username"
            #   valueFrom:
            #     secretKeyRef:
            #       name: smtp-secret
            #       key: smtp-username
            # - name: "Settings__Smtp__Password"
            #   valueFrom: 
            #     secretKeyRef:
            #       name: smtp-secret
            #       key: smtp-password
            # - name: "Settings__Sms__Type"
            #   value: "GatewayApi"
            # - name: "Settings__Sms__FromName"
            #   value: "My company name"
            # - name: "Settings__Sms__ApiUrl"
            #   value: "https://gatewayapi.eu/rest/mtsms"
            # - name: "Settings__Sms__ClientSecret"
            #   valueFrom: 
            #     secretKeyRef:
            #       name: sms-secret
            #       key: sms-secret
            - name: "Settings__Options__Log"
              value: "OpenSearchAndStdoutErrors"
            - name: "Settings__Options__DataStorage"
              value: "MongoDb"
            - name: "Settings__Options__Cache"
              value: "MongoDb"
            - name: "Settings__Options__DataCache"
              value: "None"
            - name: OPENSEARCH_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: opensearch-secret
                  key: opensearch-password
            - name: "Settings__OpenSearch__Nodes__0"
              value: "https://admin:$(OPENSEARCH_PASSWORD)@opensearch.foxids.svc.cluster.local:9200"
            - name: "Settings__OpenSearch__AllowInsecureCertificates" 
              value: "true" # Accept self-signed certificate (disable after adding trusted certs)
            - name: "Settings__OpenSearch__LogLifetime"
              value: "Max180Days"
            - name: MONGODB_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb-foxids-password
            - name: "Settings__MongoDb__ConnectionString"
              value: "mongodb://foxids:$(MONGODB_PASSWORD)@mongodb-0.mongodb-headless.foxids.svc.cluster.local,mongodb-1.mongodb-headless.foxids.svc.cluster.local,mongodb-2.mongodb-headless.foxids.svc.cluster.local/?replicaSet=mongodb&authSource=FoxIDs"
          livenessProbe:
            httpGet:
              path: /health
              port: 8800
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              cpu: "500m"
              memory: "256Mi"
            limits:
              cpu: "900m"
              memory: "512Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foxids-control-deployment
  labels:
    app: foxids-control
spec:
  replicas: 3
  selector:
    matchLabels:
      app: foxids-control
  template:
    metadata:
      labels:
        app: foxids-control
    spec:
      containers:
        - name: foxids-control
          #image: foxids/foxids-control:2.2.2
          image: foxids/foxids-control:latest-test
          imagePullPolicy: Always
          ports:
            - containerPort: 8800
          env:
            - name: "ASPNETCORE_URLS"
              value: "http://+:8800"
            - name: "Settings__UseHttp"
              value: "true"
            - name: "Settings__TrustProxySchemeHeader"
              value: "true"
            - name: "Settings__FoxIDsEndpoint"
              value: "https://id.test-multi-nodes.foxids.com" 
            - name: "Settings__FoxIDsBackendEndpoint"
              value: "http://foxids:8800"
            - name: "Settings__FoxIDsControlEndpoint"
              value: "https://control.test-multi-nodes.foxids.com"
            - name: "Settings__MasterSeedEnabled"
              value: "true"   # Enables seeding of master tenant artifacts
            - name: "Settings__MainTenantSeedEnabled"
              value: "true"   # Enables seeding of the main tenant
            - name: "Settings__Address__CompanyName"
              value: "My company name"
            - name: "Settings__Address__AddressLine1"
              value: "My company address"
            - name: "Settings__Address__PostalCode"
              value: "0000"
            - name: "Settings__Address__City"
              value: "My company city"
            - name: "Settings__Address__Country"
              value: "My company country"
            - name: "Settings__Options__Log"
              value: "OpenSearchAndStdoutErrors"
            - name: "Settings__Options__DataStorage"
              value: "MongoDb"
            - name: "Settings__Options__Cache"
              value: "MongoDb"
            - name: "Settings__Options__DataCache"
              value: "None"
            - name: OPENSEARCH_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: opensearch-secret
                  key: opensearch-password
            - name: "Settings__OpenSearch__Nodes__0"
              value: "https://admin:$(OPENSEARCH_PASSWORD)@opensearch.foxids.svc.cluster.local:9200"
            - name: "Settings__OpenSearch__AllowInsecureCertificates" 
              value: "true" # Accept self-signed certificate (replace when using trusted certs)
            - name: "Settings__OpenSearch__LogLifetime"
              value: "Max180Days"
            - name: MONGODB_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb-foxids-password
            - name: "Settings__MongoDb__ConnectionString"
              value: "mongodb://foxids:$(MONGODB_PASSWORD)@mongodb-0.mongodb-headless.foxids.svc.cluster.local,mongodb-1.mongodb-headless.foxids.svc.cluster.local,mongodb-2.mongodb-headless.foxids.svc.cluster.local/?replicaSet=mongodb&authSource=FoxIDs"
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8800
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              cpu: "300m"
              memory: "256Mi"
            limits:
              cpu: "600m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: foxids
spec:
  ports:
    - port: 8800
      targetPort: 8800
      protocol: TCP
  type: ClusterIP
  selector:
    app: foxids
---
apiVersion: v1
kind: Service
metadata:
  name: foxids-control
spec:
  ports:
    - port: 8800
      targetPort: 8800
      protocol: TCP
  type: ClusterIP
  selector:
    app: foxids-control
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: foxids-restart
spec:
  # Every 25 hours (0 */25 * * *)
  schedule: "0 */25 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: kubectl
              image: bitnami/kubectl:latest
              command:
                - /bin/sh
                - -c
                - |
                  kubectl patch deployment foxids-deployment -n $(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace) -p \
                    "{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"kubectl.kubernetes.io/restartedAt\":\"$(date +%Y-%m-%dT%H:%M:%S)\"}}}}}"
                  kubectl patch deployment foxids-control-deployment -n $(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace) -p \
                    "{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"kubectl.kubernetes.io/restartedAt\":\"$(date +%Y-%m-%dT%H:%M:%S)\"}}}}}"
              resources:
                requests:
                  cpu: 20m
                  memory: 32Mi
                limits:
                  cpu: 100m
                  memory: 64Mi
          serviceAccountName: default